function ExportResults(Results,fileName,outFolder)

% ==========================================================
% ExportResults
%
% Exports calcium synchrony pipeline results into Excel
%
% Sheets:
%   Summary
%   Pearson
%   CrossCorrelation
%   STTC
%   TimeTailed
%   LocalGlobal
%   GraphTheory
%   Bursts
%
% ==========================================================


if ~exist(outFolder,'dir')
    mkdir(outFolder)
end


excelFile = fullfile(outFolder,...
    [fileName '_SynchronyResults.xlsx']);

% Summary

Time5 = mean(Results.TimeTailedSynchrony(:,1),'omitnan');

Time10 = mean(Results.TimeTailedSynchrony(:,2),'omitnan');

Time30 = mean(Results.TimeTailedSynchrony(:,3),'omitnan');


Summary = table(...
    Results.GlobalPearson,...
    Results.GlobalSTTC,...
    Time5,...
    Time10,...
    Time30,...
    Results.LocalPearson,...
    Results.PearsonLocalGlobalRatio,...
    Results.LocalSTTC,...
    Results.STTCLocalGlobalRatio,...
    Results.NetworkDensity,...
    mean(Results.Degree,'omitnan'),...
    mean(Results.ClusteringCoefficient,'omitnan'),...
    Results.NumBursts,...
    'VariableNames',...
    {'GlobalPearson',...
    'GlobalSTTC',...
    'TimeTailed5s',...
    'TimeTailed10s',...
    'TimeTailed30s',...
    'LocalPearson',...
    'PearsonLocalGlobalRatio',...
    'LocalSTTC',...
    'STTCLocalGlobalRatio',...
    'NetworkDensity',...
    'MeanDegree',...
    'MeanClustering',...
    'NumberOfBursts'});

% Export matrices

writetable(Summary,...
    excelFile,...
    'Sheet','Summary');


writematrix(Results.Pearson,...
    excelFile,...
    'Sheet','Pearson');


writematrix(Results.CrossCorr,...
    excelFile,...
    'Sheet','CrossCorrelation');


writematrix(Results.STTCMatrix,...
    excelFile,...
    'Sheet','STTC');


% Time-tailed synchrony

TT = Results.TimeTailedSynchrony;


TimeTailedTable = table(...
    (1:size(TT,1))',...
    Results.TimeTailedTimeSeconds(:),...
    TT(:,1),...
    TT(:,2),...
    TT(:,3),...
    'VariableNames',...
    {'Frame',...
    'TimeSeconds',...
    'Synchrony_5s',...
    'Synchrony_10s',...
    'Synchrony_30s'});


writetable(TimeTailedTable,...
    excelFile,...
    'Sheet','TimeTailed');


% Local / Global synchrony

% Neuron-level values

NeuronLocalTable = table(...
    (1:length(Results.LocalPearsonNeuron))',...
    Results.LocalPearsonNeuron,...
    Results.LocalSTTCNeuron,...
    'VariableNames',...
    {'Neuron',...
    'LocalPearson',...
    'LocalSTTC'});


writetable(NeuronLocalTable,...
    excelFile,...
    'Sheet','LocalSynchrony_Neurons');


% Global summary values

LocalGlobalSummary = table(...
    Results.LocalPearson,...
    Results.PearsonLocalGlobalRatio,...
    Results.LocalSTTC,...
    Results.STTCLocalGlobalRatio,...
    Results.MeanLocalSynchrony,...
    Results.MeanSpatialSynchrony,...
    Results.LocalGlobalRatio,...
    'VariableNames',...
    {'MeanLocalPearson',...
    'PearsonLocalGlobalRatio',...
    'MeanLocalSTTC',...
    'STTCLocalGlobalRatio',...
    'MeanFunctionalLocal',...
    'MeanSpatialLocal',...
    'LocalGlobalRatio'});


writetable(LocalGlobalSummary,...
    excelFile,...
    'Sheet','LocalGlobal_Summary');

% Graph theory

GraphTable = table(...
    Results.Degree,...
    Results.ClusteringCoefficient,...
    Results.Betweenness,...
    'VariableNames',...
    {'Degree',...
    'ClusteringCoefficient',...
    'Betweenness'});


writetable(GraphTable,...
    excelFile,...
    'Sheet','GraphTheory');


writematrix(Results.AdjacencyMatrix,...
    excelFile,...
    'Sheet','Adjacency');

% Bursts

% Burst event table

BurstTable = table(...
    Results.BurstStart(:),...
    Results.BurstEnd(:),...
    Results.BurstDuration(:),...
    'VariableNames',...
    {'StartFrame',...
    'EndFrame',...
    'DurationFrames'});


writetable(BurstTable,...
    excelFile,...
    'Sheet','BurstEvents');


% Population activity trace

PopulationTable = table(...
    (1:length(Results.PopulationActivity))',...
    Results.PopulationActivity(:),...
    'VariableNames',...
    {'Frame',...
    'PopulationActivity'});


writetable(PopulationTable,...
    excelFile,...
    'Sheet','PopulationActivity');


disp(['Results exported: ' excelFile])


end